# Generated by Django 5.0.6 on 2024-06-10 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fakultas_alter_dosen_fakultas_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosen',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
