# Generated by Django 5.0.6 on 2024-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dosen_created_dosen_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
