# Generated by Django 5.0.6 on 2024-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dosen_options_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
