# Generated by Django 5.0.6 on 2024-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_dosengrade_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosengrade',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
